---
#security guidelines for serversin ansible
- name: security guidlines for servers
  hosts: ubuntu
  become: yes
  gather_facts: yes
  vars:
          ubuntu_user_password: ansible
          ubuntu_deploy_user: deploy
          ubuntu_deploy_password: deploy
          logwatch_email: ramsaik2018@gmail.com
          ubuntu_common_deploy_public_keys: ~/.ssh/id_rsa.pub
          ubuntu_common_required_packages:
                  - ufw
                  - fail2ban
                  - unattended-upgrades
                  - logwatch
          ubuntu_optional_packages:
                  - mosh
                  - vim
          ubuntu_packages: 
                  - postfix 
                  - mailutils 
                  - libsasl2-2 
                  - ca-certificates 
                  - libsasl2-modules           
          ubuntu_common_ssh_port: 22
          ubuntu_mosh_from_port: 1
          ubuntu_mosh_to_port: 60010
  tasks:
          - name: change password for user account
            user: name=ansible password="{{ubuntu_user_password}}"
    
          - name: Add User deploy
            user: name="{{ubuntu_deploy_user}}" password="{{ubuntu_deploy_password}}"  

          - name: Add authorized keys for deploy user
            authorized_key: user="{{ubuntu_deploy_user}}" key="{{lookup('file', item)}}"
            with_items: ~/.ssh/id_rsa.pub
           
          - name: Add deploy user to sudoers
            lineinfile: dest=/etc/sudoers
                        regexp="{{ ubuntu_deploy_user }} ALL"
                        line="{{ ubuntu_deploy_user }} ALL=(ALL) ALL"
                        state=present

          - name: Update APT package cache
            apt: update_cache=yes cache_valid_time=3600

          - name: Upgrade APT to the latest packages
            apt: upgrade=safe

          - name: install uncomplicated firewall
            apt: state=present pkg={{ item }}
            with_items: "{{ ubuntu_common_required_packages }}"

          - name: Install optional packages
            apt: state=present pkg={{ item }}
            with_items: "{{ ubuntu_optional_packages }}"

          - name: Adjust APT update intervals
            copy: src=apt-periodic dest=/etc/apt/apt.conf.d/10periodic

          - name: Setup ufw
            ufw: state=enabled policy=deny

          - name: Allow ssh traffic
            ufw: rule=allow port="{{ ubuntu_common_ssh_port}}" proto=tcp

          - name: Allow mosh traffic
            ufw: rule=allow proto=udp port={{ ubuntu_mosh_from_port }}:{{ ubuntu_mosh_to_port }}
            when: "'mosh' in ubuntu_optional_packages"

          - name: Set up Postfix to relay mail
            debconf: name=postfix
                     question='{{ item.question }}'
                     value='{{ item.value }}'
                     vtype='{{ item.vtype }}'
            with_items:
                - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
                - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

          - name: Email log summary daily
            lineinfile: dest=/etc/cron.daily/00logwatch
                        regexp="^/usr/sbin/logwatch"
                        line="/usr/sbin/logwatch --output mail --mailto "{{logwatch_email}}" --detail high"
                        state=present create=yes

          - name: extra packages
            apt: state=present pkg={{ item }}
            with_items: "{{ubuntu_packages}}"

          - name: copy main.cf file
            blockinfile: path=/etc/postfix/main.cf block="{{ lookup('file','main.cf')}}" create=yes state=present
            
          - name: user credentials of smtp  
            copy:
                 src: sasl_passwd
                 dest: /etc/postfix/sasl_passwd
                 follow: no    
        
          - name: Fix permission and update postfix config to use sasl_passwd file
            shell: "sudo chmod 400 /etc/postfix/sasl_passwd && sudo postmap /etc/postfix/sasl_passwd"

          - name:  validate certificates to avoid running into error
            shell: "cat /etc/ssl/certs/thawte_Primary_Root_CA.pem | sudo tee -a /etc/postfix/cacert.pem "  
          
          - name:  reload postfix config for changes to take effect
            shell: "sudo /etc/init.d/postfix reload"

          - name:  sending mail
            shell: " sudo /usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
            
          - name: Change ssh port
            lineinfile: dest=/etc/ssh/sshd_config
                        regexp="^Port\s"
                        line= "Port {{ubuntu_common_ssh_port}}"
                        state=present
            notify: Restart ssh 

          - name: Disallow password authentication
            lineinfile: dest=/etc/ssh/sshd_config
                        regexp="^PasswordAuthentication"
                        line="PasswordAuthentication no"
                        state=present
            notify: Restart ssh

          - name: Disallow root SSH access
            lineinfile: dest=/etc/ssh/sshd_config
                        regexp="^PermitRootLogin"
                        line="PermitRootLogin no"
                        state=present
            notify: Restart ssh
            tags: ssh

  handlers:
          - name: Restart ssh
            service: name=ssh state=restarted

