namespace: "namespace_name"
name: "collection_name"
version: "1.0.0"
readme: "README.md"
authors:
    - Srajit Srivastav
dependencies: []
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://github.com/srajitsrivastav/Ansible"
