
---
 #An Ansible PlayBook to demonstrate Weekly System Rebootn
- hosts: all
  #user: ansible
  #become: true
  connection: ssh
  tasks:
          - name:  upgrades all packages in nodes with yum module
            yum: name=* state=latest
            when: ansible_os_family=="RedHat"

          - name: Reboot node
            command: "{{ item }}"
            with_items:
                    - sleep 5
                    - /sbin/reboot
            async: 1
            poll: 0

          - name: wait for 300 seconds for port 22 to become open and contain OpenSSH
            become_user: root
            wait_for:
                   port: 22
                   host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
                   search_regex: OpenSSH
                   delay: 10
                   #timeout: 300

